models_dir: /Users/peter/isys/stl_bladders
bladder_model_regex: '^(?!.*\._|.*\.DS).*smooth'  # because ignore mac's ._ files...
camera_intrinsics: spec_files/cam_params.json
bladder_volume: .0004  # m^3
output_folder: test/output
samples_per_model: 2
distance_range: [0.000, 0.04]
view_angle_max: [45, 45, 45]
emission_range: [200, 200]
render_normals: true
clear_output_folder: true
materials_files:
  - ./blender/bladder_material.blend
bladder_materials:
  - bladder_wall

bladder_material_config:
  volume_scatter_density:  1.0
  volume_scatter_anisotropy: 0.6
  volume_absorbtion_density: 1.0

resection_loop:
  wire_stl: /Users/peter/isys/resection_loop/tueb_wire.STL
  insulation_stl: /Users/peter/isys/resection_loop/tueb_insulation.STL
  extension_direction: [0, -1, 0]
  no_clip_points: [[0.0, 0.0, -2.5], [2.0, 0.0, 0.0], [-2.0, 0.0, 0.0]]

endo_light:
  stl_file: /Users/peter/isys/endo_lights/tuebingen_light.STL
  emission_color: [1.0, 1.0, 1.0, 1.0]
  emission_strength: 50
  scaling_factor: .001
  euler_rotation: [90, 0, 90]

tumor_particles:
  stl_file:  /Users/peter/isys/low_poly_cauliflower.stl
  amount: 20
  volume_max: 0.0000001 #m^3
  scaling_range: [0.1, 2]
  rotation_range: [0, 360]
  rotation_mode: align_to_surface

diverticulum:
  amount: 1
  subdivisions_sphere: 4
  radius_sphere_range: [ 0.001, 0.02 ] #m
  translation_range: [ -0.7, 0.7 ]

shrinkwrap_wire:
<<<<<<< HEAD
   wrap_mode: "INSIDE"
   distance: .005
   use_track_normal: false
   shrinkwrap_type: "PROJECT"
   project_axis: "POS_Z"

shrinkwrap_tool:
   wrap_mode: "INSIDE"
   shrinkwrap_type: "NEAREST_SURFACE"
   distance: 0.005
   use_track_normal: false

blender:
  unit_settings:
    length_unit: "MILLIMETERS"
  render:
    resolution_percentage: 40
    image_settings:
      color_mode: 'RGB'
    engine: 'CYCLES'
    threads_mode: 'FIXED'
    threads: 6
    use_persistent_data: true
  cycles:
    adaptive_min_samples: 64
    adaptive_max_samples: 128
    denoiser: "OPENIMAGEDENOISE"
    device: 'GPU'
    device_type: "METAL"
  use_nodes: true

