models_dir: /Users/peter/isys/bladder_models
bladder_model_regex: '.*smooth.'
camera_intrinsics: test/cam_params.json
bladder_volume: .0004  # m^3
output_folder: test/output
samples_per_model: 20
distance_range: [0.005, 0.04]
view_angle_max: [45, 45, 45]
emission_range: [30, 30]
render_normals: true
clear_output_folder: True

endo_light:
  stl_file: /Users/peter/isys/endo_lights/ITO_light.stl
  emission_color: [1.0, 1.0, 1.0, 1.0]
  emission_strength: 50
  scaling_factor: .001
  euler_rotation: [90, 0, 90]

tumor_particles:
  stl_file:  /Users/peter/isys/bladder_models/labels-0_bladder_smooth.stl
  amount: 50
  volume_max: 0.0000001 #m^3
  scaling_range: [0.1, 1]
  rotation_range: [0, 360]

diverticulum:
  amount: 2
  subdivisions_sphere: 4
  radius_sphere_range: [ 0.001, 0.02 ] #m
  radius_opening_range: [ 0.001, 0.003 ] #m

subdivision_mod:

#displacement_modifier:
#  texture_coords: "UV"
#  strength: 0.01
#  texture: "Texture"
#  mid_level: 0.1

shrinkwrap:
  wrap_mode: "ON_SURFACE"
  distance: .01
  use_track_normal: false
  shrinkwrap_type: "PROJECT"
  project_axis: "NEG_Z"

blender:
  unit_settings:
    length_unit: "MILLIMETERS"
  render:
    resolution_percentage: 50
    image_settings:
      color_mode: 'RGB'
    engine: 'CYCLES'
    threads_mode: 'FIXED'
    threads: 6
  cycles:
    adaptive_min_samples: 64
    adaptive_max_samples: 128
    denoiser: "OPENIMAGEDENOISE"
    device: 'GPU'
  use_nodes: true

