log_directory: ./retrain_logs
print_config: true
adaptive_gating: false
predict_normals: false
mode: synthetic
training_stage: train
split_save_dir: ./tool_splits
synthetic_config:
  lr: 1e-4
  max_epochs: 300
  data_roles:
    - color
    - depth
  data_directories:
    - /Users/peter/isys/2023_01_23_w_tool/color
    - /Users/peter/isys/2023_01_23_w_tool/depth
  training_split: {'train': .8, 'validate': 0.2, 'test': ".*00015.*"}
  resume_from_checkpoint: /Users/peter/isys/model_weights/synthetic-epoch=22-step=52923.ckpt
gan_config:
  source_images: /Users/peter/isys/output/color
  synthetic_base_model: ./logs/synthetic/lightning_logs/version_47/checkpoints/epoch=7-step=8.ckpt
  synth_split: {'train': .6, 'validate': .2, 'test': .2}
  generate_data: False
  videos_folder:  /Users/peter/isys/videos
  image_output_folder: ./gan_data
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 2