log_directory: ./logs
print_config: true
adaptive_gating: true
mode: gan
training_stage: train
split_save_dir: ./splits
synthetic_config:
  max_epochs: 300
  data_roles:
    - color
    - depth
  data_directories:
    - /Users/peter/isys/output/color
    - /Users/peter/isys/output/depth
  training_split: {'train': .6, 'validate': 0.4, 'test': ".*00015.*"}
  resume_from_checkpoint: ./logs/synthetic/lightning_logs/version_47/checkpoints/epoch=7-step=8.ckpt
gan_config:
  source_images: /Users/peter/isys/output/color
  synthetic_base_model: ./logs/synthetic/lightning_logs/version_47/checkpoints/epoch=7-step=8.ckpt
  synth_split: {'train': .6, 'validate': .2, 'test': .2}
  generate_data: False
  videos_folder:  /Users/peter/isys/videos
  image_output_folder: ./gan_data
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 2