log_directory: ./logs
adaptive_gating: true
mode: synthetic
training_stage: train
split_save_dir: ./splits
synthetic_config:
  max_epochs: 300
  data_roles:
    - color
    - depth
    - normals
  data_directories:
    - /Users/peter/isys/output/color
    - /Users/peter/isys/output/depth
#    - /Users/peter/isys/output/normal
  training_split: {'train': .6, 'validate': 0.4, 'test': ".*00015.*"}
gan_config:
  source_images: /Users/peter/isys/output/color
  synthetic_base_model: ./logs/synthetic/lightning_logs/version_11/checkpoints/epoch=9-step=10.ckpt
  generate_data: False
  videos_folder:  /Users/peter/isys/videos
  image_output_folder: ./gan_data
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu