glog_directory: ./logs
print_config: true
adaptive_gating: false
mode: synthetic
training_stage: train
inverse_depth: true
split_save_dir: splits
num_workers: 8
synthetic_config:
  max_epochs: 6000
  data_roles:
    - color
    - depth
   # - normals
  data_directories:
<<<<<<< HEAD
<<<<<<< HEAD
    -
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/color
    -
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/depth

#    - /Users/peter/isys/output/normal
  batch_size: 64
  accumulate_grad_batches: 2
  training_split_file: ../splits/syntetic/training_split.json
  training_split: {'train': .85, 'validate': 0.15, 'test': ".*102_bladder.*"}
  #resume_from_checkpoint: logs/synthetic/lightning_logs/version_0/checkpoints/epoch=11-step=312.ckpt
  lr: 0.008
  monitor_metric: val_rel_err
  val_check_interval: 1.0
  grad_loss_factor: 1.0
  callbacks:
    early_stop_patience: null
    lr_monitoring: true
    lr_monitor_interval: step

gan_config:
  max_epochs: 300
  batch_size: 16
  val_check_interval: 1.0
  source_images:
    - ../datasets/Particles_diverticulum_no_tool_materials_221215/color
  synthetic_base_model: logs/synthetic/lightning_logs/version_44/checkpoints/epoch=3459-step=51900.ckpt
  generate_data: False
  videos_folder:  ../datasets/gan_data
  image_output_folder: ../datasets/gan_data
  align_scales: false
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 1
  gradient_clip_val: 0.3
  fast_dev_run: false