glog_directory: ./logs
print_config: true
adaptive_gating: false
mode: synthetic
training_stage: train
inverse_depth: true
split_save_dir: splits
num_workers: 8
synthetic_config:
  max_epochs: 300
  data_roles:
    - color
    - depth
   # - normals
  data_directories:
    -
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/color/bland_bladder_wall
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/color/bladder_wall
    -
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/depth/bland_bladder_wall
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/depth/bladder_wall

#    - /Users/peter/isys/output/normal
  batch_size: 44
  training_split: {'train': .85, 'validate': 0.15, 'test': ".*12_bladder.*"}
  #resume_from_checkpoint: logs/synthetic/lightning_logs/version_0/checkpoints/epoch=11-step=312.ckpt
  monitor_metric: val_rmse
  val_check_interval: 1.0
  grad_loss_factor: 0
  callbacks:
    early_stop_patience: 15
    lr_monitoring: true
    lr_monitor_interval: step

gan_config:
  source_images: ../datasets/particles_diverticulum_tool_no_material/output/color
  synthetic_base_model: logs/synthetic/lightning_logs/version_17/checkpoints/epoch=45-step=506.ckpt
  generate_data: False
  videos_folder:  ../datasets/gan_data
  image_output_folder: ../datasets/gan_data
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 1
  gradient_clip_val: 0.3
  fast_dev_run: false