glog_directory: ./logs
print_config: true
adaptive_gating: true
mode: gan
training_stage: train
split_save_dir: splits
num_workers: 8
synthetic_config:
  max_epochs: 6000
  data_roles:
    - color
    - depth
   # - normals
  data_directories:
    -
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/color
    -
      - ../datasets/Particles_diverticulum_no_tool_materials_221215/depth

#    - /Users/peter/isys/output/normal
  batch_size: 60
  accumulate_grad_batches: 4
  training_split: {'train': .85, 'validate': 0.15, 'test': ".*102_bladder.*"}
  #resume_from_checkpoint: logs/synthetic/lightning_logs/version_0/checkpoints/epoch=11-step=312.ckpt
  monitor_metric: val_rel_err
  val_check_interval: 1.0
  grad_loss_factor: 1.0
  callbacks:
    early_stop_patience: null
    lr_monitoring: true
    lr_monitor_interval: step

gan_config:
  source_images: ../datasets/particles_diverticulum_tool_no_material/output/color
  synthetic_base_model: logs/synthetic/lightning_logs/version_17/checkpoints/epoch=45-step=506.ckpt
  generate_data: False
  videos_folder:  ../datasets/gan_data
  image_output_folder: ../datasets/gan_data
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 2
  fast_dev_run: false